export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "CLEAR_ALERT";
export const REGISTER_USER_SUCCESS = "CLEAR_ALERT";
export const REGISTER_USER_ERROR = "CLEAR_ALERT";

export const LOGIN_USER_BEGIN = "CLEAR_ALERT";
export const LOGIN_USER_SUCCESS = "CLEAR_ALERT";
export const LOGIN_USER_ERROR = "CLEAR_ALERT";
